name = "releam"
version = "0.3.1"

description = "Releam is an opinionated gleam release and changelog generation tool based on conventional commit"
licences = ["Apache-2.0"]
repository = { type = "github", user = "pedraal", repo = "releam" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
tom = ">= 1.0.1 and < 2.0.0"
gleamsver = ">= 1.0.1 and < 2.0.0"
glint = ">= 1.0.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
snag = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[releam]
auto_push = true
